name: Update Research Papers

on:
  schedule:
    # Runs at 00:00 UTC on the 1st day of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false # Important for push actions
        fetch-depth: 0 # Fetch all history for proper Git operations

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run research scraper
      run: python research_scraper.py

    - name: Commit and push if changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        git add data/*.json
        
        git diff --quiet --exit-code || (
          git commit -m "Automated: Update research papers [skip ci]"
          git push
        )
      env:
        # GITHUB_TOKEN is automatically provided by GitHub Actions for repository write access
        # No need to manually create a PAT if you are pushing to the same repo.
        # However, for advanced scenarios or different repos, you might need a PAT:
        # GH_TOKEN: ${{ secrets.YOUR_PAT_SECRET_NAME }}
